---
title: "Data_analysis"
author: "Aoi, Ester, Jillian"
date: "4/23/2018"
output: html_document
---


```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(mosaic)
# library(forcats)
# library(plyr)
```


```{r}
oscars <- read.csv("https://raw.githubusercontent.com/BuzzFeedNews/2018-03-oscars-script-diversity-analysis/master/data/actor-metrics.csv")
```

```{r}
# main characters
main_character <- oscars %>%
  filter(words >= 1000)

# sub characters
sub_character <- oscars %>%
  filter(words < 1000)

# female actors
actress <- oscars %>%
  filter(gender == "female")

# main female actor 
main_actress <- actress %>%
  filter(words >= 1000)

# actors who are poc
poc_actor <- oscars %>%
  filter (race_simple == "POC")

#main character actors who are poc 
main_poc_actor <- main_character %>%
  filter (race_simple == "POC") 

#sub character actors who are poc 
sub_poc_actor <- sub_character %>%
  filter(race_simple == "POC")

# main white actor 
main_white_actor <- oscars %>% 
  filter(race_simple == "White") %>%
  filter(words >= 1000)

# sub white actor 
sub_white_actor <- oscars %>%  
  filter(race_simple == "White") %>%
  filter(words < 1000)
```

```{r}
#top 10 white males who have the most word count
top_white <- main_white_actor %>%
  arrange(desc(words)) %>%
  head(5)
id <- rownames(top_white)
top_white <- cbind(id = id, top_white)


#top 10 POC actor/actress who have the most word count
top_poc <- poc_actor %>%
  arrange(desc(words)) %>%
  head(5)
id <- rownames(top_poc)
top_poc <- cbind(id = id, top_poc)

top_race <- full_join(top_white, top_poc)


#white, poc 
ggplot(top_race) + 
  geom_bar (aes(x=id, y = words, fill = race_simple), stat = "identity", position = "dodge") +
  labs(x = "Top 5 Actors (highest word counts)", y = "Total Word Count", title = "POC vs White Actor Word Counts", fill = "Actor Race")
```

```{r}
#top 10 female who have the most word count
top_actress <- main_actress %>%
  arrange(desc(words)) %>%
  head(5)

id <- rownames(top_actress)
top_actress <- cbind(id = id, top_actress)

#top 10 male who have the most word count
top_actor <- oscars %>%
  filter(gender == "male") %>%
  arrange(desc(words)) %>%
  head(5)

id <- rownames(top_actor)
top_actor <- cbind(id = id, top_actor)

top_gender <- full_join(top_actor, top_actress)


#female, male 
ggplot(top_gender) + 
  geom_bar (aes(x = id, y = words, fill = gender), stat = "identity", position = "dodge") +
  labs(x = "Top 5 Actors (highest word counts)", y = "Total Word Count", title = "Female vs Male Actor Word Counts", fill = "Gender")

```


```{r}
#time vs word count in race 

race_words <- oscars %>%
  dplyr::group_by(year, race_simple) %>%
  dplyr::summarise(words_sum = sum(words))

total_words <- oscars %>%
  dplyr::group_by(year) %>%
  dplyr::summarise(total = sum(words))

fin_race_words <- inner_join(race_words,total_words)

fin_race_words <- fin_race_words %>%
  mutate(prop = words_sum/total*100)
#%>%
  #ddply(fin_race_words, .(year),transform, pos = cumsum(percentage) - (0.5 * percentage))


ggplot(fin_race_words, aes(x = as.factor(year), y = prop, fill = race_simple)) + 
  geom_bar(stat = "identity") +
  labs(x = "Years", y = "The Proportion of Main Characters", title = "The Proportion of White vs POC Actors", fill = "Race")

#+
  #geom_text(aes(x = year, y = pos, label = paste0(percentage,"%")), size = 4) 
  
  
```


```{r}
#time vs word count in gender 

gender_words <- oscars %>%
  dplyr::group_by(year, gender) %>%
  dplyr::summarise(words_sum = sum(words)) 

g_total_words <- oscars %>%
  dplyr::group_by(year) %>%
  dplyr::summarise(total = sum(words))

fin_g_words <- inner_join(gender_words,g_total_words)

fin_g_words <- fin_g_words %>%
  mutate(prop = words_sum/total*100)

ggplot(fin_g_words, aes(x = as.factor(year), y = prop, fill = gender)) + 
  geom_bar(stat = "identity") +
  labs(x = "Years", y = "The Proportion of Actor / Actress", title = "The Proportion of Actor vs Actress", fill = "Gender")
```

```{r}
#actors, race, gender

#white male
white_males <- main_white_actor %>%
  dplyr::summarise(white_m = n())

#white female
white_female <- main_actress %>%
  filter(race_simple == "White") %>%
  dplyr::summarise(white_f = n())

#POC male 
poc_male <- poc_actor %>%
  filter(gender == "male") %>%
  dplyr::summarise(poc_m = n())


all <- white_males

all <- rbind(all, "white_f" = 13) %>%
  rbind ("poc_m" = 17) %>%
  rbind("poc_f" = 13)

names(all)[1]<-"number"

all <- all %>%
  mutate(prop = number/ sum(number)*100)

rownames(all) <-c("white_m", "white_f", "poc_m", "poc_f" )

all <- cbind(rownames(all), all)
rownames(all) <- NULL
colnames(all) <- c("type","number","prop")

all <- all %>%
  mutate(all = ifelse(number>10, "", ""))

ggplot(all, aes(x = all, y = prop, fill = type)) +
  geom_bar(stat = "identity") +
  ggplot2::labs(x = "All Actors (1989, 2015, 2017)", y = "The Proportion of Main Characters", title = "The Proportion of White vs POC Actors", fill = "Gender and Race") + 
  scale_fill_discrete(breaks = c("poc_f", "poc_m", "white_f", "white_m"), labels = c("POC Female", "POC Male", "White Female", "White Male"))


```

```{r}
mod <- lm(words ~ as.factor(year) + gender + race_simple, data = oscars)

summary(mod)

plot(mod, which = c(1,2))
```

